# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Qi Wang"
title_separator          : "-"
name                     : &name "Qi Wang"
description              : &description "Personal website of Qi Wang, Postdoctoral Associate at Boston University. Research on healthcare operations management, healthcare AI, AI and the future of work, and supply chain."
url                      : "https://qiwang-katherine.github.io"
baseurl                  : ""
repository               : "qiwang-katherine/qiwang-katherine.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Qi Wang"
  pronouns         : 
  bio              : "Healthcare operations management, healthcare AI, AI and the future of work, and supply chain."
  location         : "Boston, US"
  employer         : "Boston University"
  uri              : 
  email            : "qiwangqw@bu.edu"
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=mcfE_OgAAAAJ&hl=en"
  impactstory      :
  orcid            :
  semantic         :
  pubmed           :
  researchgate     :
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "qiwang-katherine"
  kaggle           :
  stackoverflow    :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  instagram        :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true
